export let firstParts = $state([
    "Worbleshire",
    "Chesterham",
    "Buckington",
    "Foxbury",
    "Hampsmere",
    "Thistlewick",
    "Brighthaven",
    "Kensbrook",
    "Millsworth",
    "Ashington",
    "Pendlebury",
    "Wembley",
    "Thornbury",
    "Wiltonshire",
    "Queensmere",
    "Rockingham",
    "Moorfield",
    "Brixworth",
    "Stratford",
    "Chelmswick",
    "Nottingley",
    "Kingsbury",
    "Westbrook",
    "Finchley",
    "Dartmouth",
    "Brackley",
    "Eastwick",
    "Merriweather",
    "Southwick",
    "Ravenspur",
    "Blackbridge",
    "Winchelsea",
    "Hampsworth",
    "Kingsbridge",
    "Marlborough",
    "Northbury",
    "Rothbury",
    "Staveley",
    "Twickford",
    "Uxbridge",
    "Wetherby",
    "Yarmouth",
    "Dovercliff",
    "Elmsworth",
    "Farnworth",
    "Guildford",
    "Harbury",
    "Ivybridge",
    "Kenilworth",
    "Lancaster"
]);

export let secondParts = $state([
    "United F.C.",
    "Town F.C.",
    "City F.C.",
    "Athletic",
    "Rovers",
    "Wanderers",
    "Albion",
    "County F.C.",
    "Forest",
    "Rangers",
    "Wednesday",
    "Hotspur",
    "Borough F.C.",
    "Villa",
    "Thistle",
    "Heath",
    "North End",
    "Stanley",
    "Alexandra",
    "Orient",
    "Vale F.C.",
    "City United",
    "Academicals",
    "Athletic Union",
    "Sporting Club",
    "Metropolitan",
    "Royal F.C.",
    "Casuals",
    "Warriors",
    "Pilgrims"
]);

