export let firstParts = $state([
    "Worbleshire",
    "Chesterham",
    "Buckington",
    "Foxbury",
    "Hampsmere",
    "Thistlewick",
    "Brighthaven",
    "Kensbrook",
    "Millsworth",
    "Ashington",
    "Pendlebury",
    "Wembley",
    "Thornbury",
    "Wiltonshire",
    "Queensmere",
    "Rockingham",
    "Moorfield",
    "Brixworth",
    "Stratford",
    "Chelmswick",
    "Nottingley",
    "Kingsbury",
    "Westbrook",
    "Finchley",
    "Dartmouth",
    "Brackley",
    "Eastwick",
    "Merriweather",
    "Southwick",
    "Ravenspur",
    "Blackbridge",
    "Wanderling",
    "Hampsworth",
    "Kingsbridge",
    "Marlborough",
    "Northbury",
    "Rothbury",
    "Staveley",
    "Twickford",
    "Uxbridge",
    "Wetherby",
    "Yarmouth",
    "Dovercliff",
    "Elmsworth",
    "Farnworth",
    "Guildford",
    "Harbury",
    "Ivybridge",
    "Kenilworth",
    "Lancaster",
    "Bravelton",
    "Windswick",
    "Sulford",
    "Bramptley",
    "Stoving",
    "Bailswick",
    "Tranbury",
    "King's Park",
    "Dolberton",
    "Pancroft",
    "Pillsbury",
    "Wheatley",
    "Crowsbury",
    "Crovington",
    "Grampton",
    "Picklebury",
    "Barnsbury",
    "Brample",
    "Buildsworth",
    "Littleborough",
    "Cremington",
    "Blocksworth",
    "Bullsbury"
]);

export let secondParts = $state([
    "United",
    "United F.C.",
    "Town",
    "Town F.C.",
    "City",
    "City F.C.",
    "Athletic",
    "Rovers",
    "Wanderers",
    "Albion",
    "County F.C.",
    "Grove F.C.",
    "Forest",
    "Rangers",
    "Wednesday",
    "Hotspur",
    "Borough F.C.",
    "Villa",
    "Thistle",
    "Heath",
    "North End",
    "Stanley",
    "Alexandra",
    "Orient",
    "Vale F.C.",
    "City United",
    "Heights F.C."
]);

