export let teams = $state({
    team1: {
        name: '',
        draftOrder: 0,
        attackers: [],
        midfielders: [],
        defenders: [],
        keepers: [],
        playerCount: 0,
        traits: [],
        transferBudget: 275.00,
        wins: 0,
        draws: 0,
        losses: 0,
        points: 0,
        goalsFor: 0,
        goalsAgainst: 0
    },
    team2: {
        name: '',
        draftOrder: 0,
        attackers: [],
        midfielders: [],
        defenders: [],
        keepers: [],
        playerCount: 0,
        traits: [],
        transferBudget: 275.00,
        wins: 0,
        draws: 0,
        losses: 0,
        points: 0,
        goalsFor: 0,
        goalsAgainst: 0
    },
    team3: {
        name: '',
        draftOrder: 0,
        attackers: [],
        midfielders: [],
        defenders: [],
        keepers: [],
        playerCount: 0,
        traits: [],
        transferBudget: 275.00,
        wins: 0,
        draws: 0,
        losses: 0,
        points: 0,
        goalsFor: 0,
        goalsAgainst: 0
    },
    team4: {
        name: '',
        draftOrder: 0,
        attackers: [],
        midfielders: [],
        defenders: [],
        keepers: [],
        playerCount: 0,
        traits: [],
        transferBudget: 275.00,
        wins: 0,
        draws: 0,
        losses: 0,
        points: 0,
        goalsFor: 0,
        goalsAgainst: 0
    },
    team5: {
        name: '',
        draftOrder: 0,
        attackers: [],
        midfielders: [],
        defenders: [],
        keepers: [],
        playerCount: 0,
        traits: [],
        transferBudget: 275.00,
        wins: 0,
        draws: 0,
        losses: 0,
        points: 0,
        goalsFor: 0,
        goalsAgainst: 0
    },
    team6: {
        name: '',
        draftOrder: 0,
        attackers: [],
        midfielders: [],
        defenders: [],
        keepers: [],
        playerCount: 0,
        traits: [],
        transferBudget: 275.00,
        wins: 0,
        draws: 0,
        losses: 0,
        points: 0,
        goalsFor: 0,
        goalsAgainst: 0
    },
    team7: {
        name: '',
        draftOrder: 0,
        attackers: [],
        midfielders: [],
        defenders: [],
        keepers: [],
        playerCount: 0,
        traits: [],
        transferBudget: 275.00,
        wins: 0,
        draws: 0,
        losses: 0,
        points: 0,
        goalsFor: 0,
        goalsAgainst: 0
    },
    team8: {
        name: '',
        draftOrder: 0,
        attackers: [],
        midfielders: [],
        defenders: [],
        keepers: [],
        playerCount: 0,
        traits: [],
        transferBudget: 275.00,
        wins: 0,
        draws: 0,
        losses: 0,
        points: 0,
        goalsFor: 0,
        goalsAgainst: 0
    },
    team9: {
        name: '',
        draftOrder: 0,
        attackers: [],
        midfielders: [],
        defenders: [],
        keepers: [],
        playerCount: 0,
        traits: [],
        transferBudget: 275.00,
        wins: 0,
        draws: 0,
        losses: 0,
        points: 0,
        goalsFor: 0,
        goalsAgainst: 0
    },
    team10: {
        name: '',
        draftOrder: 0,
        attackers: [],
        midfielders: [],
        defenders: [],
        keepers: [],
        playerCount: 0,
        traits: [],
        transferBudget: 275.00,
        wins: 0,
        draws: 0,
        losses: 0,
        points: 0,
        goalsFor: 0,
        goalsAgainst: 0
    },
    team11: {
        name: '',
        draftOrder: 0,
        attackers: [],
        midfielders: [],
        defenders: [],
        keepers: [],
        playerCount: 0,
        traits: [],
        transferBudget: 275.00,
        wins: 0,
        draws: 0,
        losses: 0,
        points: 0,
        goalsFor: 0,
        goalsAgainst: 0
    },
    team12: {
        name: '',
        draftOrder: 0,
        attackers: [],
        midfielders: [],
        defenders: [],
        keepers: [],
        playerCount: 0,
        traits: [],
        transferBudget: 275.00,
        wins: 0,
        draws: 0,
        losses: 0,
        points: 0,
        goalsFor: 0,
        goalsAgainst: 0
    },
    team13: {
        name: '',
        draftOrder: 0,
        attackers: [],
        midfielders: [],
        defenders: [],
        keepers: [],
        playerCount: 0,
        traits: [],
        transferBudget: 275.00,
        wins: 0,
        draws: 0,
        losses: 0,
        points: 0,
        goalsFor: 0,
        goalsAgainst: 0
    }
});

export let playerTeam = $state({
    name: '',
    draftOrder: 0,
    attackers: [],
    midfielders: [],
    defenders: [],
    keepers: [],
    playerCount: 0,
    transferBudget: 275,
    wins: 0,
    draws: 0,
    losses: 0,
    points: 0,
    goalsFor: 0,
    goalsAgainst: 0
});

export let draft = $state({
    started: false,
    complete: false,
    currentRound: 1,
    currentPick: 1,
    currentTeam: '',
    nextTeam: ''
});

export let processedPlayers = $state([]);
export let gate0 = $state(false);
export let gate1 = $state(false);
export let draftOrderList = $state([]);